version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: jasoseol
    environment:
      - PROJECT_ENV=base
      - TZ=Asia/Seoul
    ports:
      - "8000:8000"
    volumes:
      - .:/webapp/server